#!/bin/bash
echo "Ahora se esta instalando Defkey... No tomara mucho"
sleep 2s
git clone https://github.com/drygdryg/wpspin.git
cd wpspin/
python setup.py install
sleep 2s
pip install colorama
echo "Defkey ha sido instalado"
echo "Ahora puedes correr el programa con python defkey.py....happy hacking"
